from enum import Enum


class AgentTableName(str, Enum):
    AN_LCL_MPMS_PLTF_DEF = "AN_LCL_MPMS_PLTF_DEF"
    AH_LCL_MPMS_PLTF_DEF = "AH_LCL_MPMS_PLTF_DEF"
    AN_LCL_MPMS_PROD_INF = "AN_LCL_MPMS_PROD_INF"
    AH_LCL_MPMS_PROD_INF = "AH_LCL_MPMS_PROD_INF"
    AN_LCL_MPMS_PROD_PRICE_INF = "AN_LCL_MPMS_PROD_PRICE_INF"
    AH_LCL_MPMS_PROD_PRICE_INF = "AH_LCL_MPMS_PROD_PRICE_INF"
    AH_LCL_MPMS_PROD_MON_RUL_INF = "AH_LCL_MPMS_PROD_MON_RUL_INF"

